### ISSUE TITLE
Build error with kernel 6.5 / 6.4 (?) - implicit declaration of function 'skb_gso_segment'

### ISSUE THREAD

**Issue by bernhardschmidt** [OpenVPN/ovpn-dco#43] opened 2023-08-21 14:34 UTC
see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1043116 . 

```
  CC [M]  /var/lib/dkms/ovpn-dco/0.0+git20230324/build/drivers/net/ovpn-dco/udp.o
/var/lib/dkms/ovpn-dco/0.0+git20230324/build/drivers/net/ovpn-dco/ovpn.c: In function 'ovpn_net_xmit':
/var/lib/dkms/ovpn-dco/0.0+git20230324/build/drivers/net/ovpn-dco/ovpn.c:432:28: error: implicit declaration of function 'skb_gso_segment'; did you mean 'skb_gso_reset'? [-Werror=implicit-function-declaration]
  432 |                 segments = skb_gso_segment(skb, 0);
      |                            ^~~~~~~~~~~~~~~
      |                            skb_gso_reset
/var/lib/dkms/ovpn-dco/0.0+git20230324/build/drivers/net/ovpn-dco/ovpn.c:432:26: warning: assignment to 'struct sk_buff *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  432 |                 segments = skb_gso_segment(skb, 0);
      |                          ^
cc1: some warnings being treated as errors
make[4]: *** [/usr/src/linux-headers-6.5.0-0-common/scripts/Makefile.build:248: /var/lib/dkms/ovpn-dco/0.0+git20230324/build/drivers/net/ovpn-dco/ovpn.o] Error 1
```

Please note that according to the bug report the kernel change causing this has been backported to 6.4-stable.

**Comment by ordex** [comment] 2023-08-21 20:47
this is a duplicate of #42 
This problem has been fixed in master, but I haven't created any tag yet. Would it help to create a tag now including this fix?

**Closed by ordex** 2023-08-21 20:47 UTC
Labels: bug, duplicate

**Comment by bernhardschmidt** [comment] 2023-08-21 20:48
> this is a duplicate of #42 This problem has been fixed in master, but I haven't created any tag yet. Would it help to create a tag now including this fix?

Aww no, sorry, missed that. Right now I'm packaging git snapshots anyway, so no tag needed.
