### ISSUE TITLE
Build error with CentOS Stream release 8

### ISSUE THREAD

**Issue by vasilko** [OpenVPN/ovpn-dco#52] opened 2023-11-06 10:21 UTC
Hellou, 
few days ago, I want to install OpenVPN server with dco feature. I use tutorial below, because standard epel release for Centos Stream 8 does not have dco support:
https://community.openvpn.net/openvpn/wiki/OpenvpnSoftwareRepos
So I use dsommers/openvpn3 repo for kmod-ovpn-dco. During dnf install (scriptlet), there was and error with building:

kernel 4.18.0-519.el8.
gcc version 8.5.0 20210514 (Red Hat 8.5.0-21).
[dco.txt](https://github.com/OpenVPN/ovpn-dco/files/13265320/dco.txt)

So, there is a bug, or I doing something wrong? So far, openvpn was working fine (last month I upgraded from 2.4.12 to 2.5.9 and now 2.6.6), but I am interesting in dco module for more speed (my multithread CPU with conecting with AES-256-GCM allows max 1Gbps throughput).
Thank you for help or infromations.
Stanislav

**Comment by ordex** [comment] 2023-11-06 10:28
Hi, thanks for the report!
I think this is a duplicate of #32 

CentOS is not being recognized and so the according compat code is no activated

**Closed** 2023-11-06 10:28 UTC
Labels: duplicate

**Comment by vasilko** [comment] 2023-11-07 09:07
Thank you for you answer. I read duplicate of this issue and understand.
Have a nice day.
