### ISSUE TITLE
netlink reports object not found

### ISSUE THREAD

**Issue by mr-liusg** [OpenVPN/ovpn-dco#51] opened 2023-09-27 15:22 UTC
After three days of steady running, suddenly

````
2023-09-27 19:04:52 us=681004 CLIENT/XXXXXX:65165 dco_new_key: netlink reports object not found, ovpn-dco unloaded?
2023-09-27 19:04:52 us=681014 CLIENT/XXXXXX:65165 dco_new_key: failed to send netlink message: No such file or directory (-2)
2023-09-27 19:04:52 us=681020 CLIENT/XXXXXX:65165 Impossible to install key material in DCO: No such file or directory
2023-09-27 19:04:52 us=681023 CLIENT/XXXXXX:65165 Exiting due to fatal error
2023-09-27 19:04:52 us=681036 CLIENT/XXXXXX:65165 Closing DCO interface
2023-09-27 19:04:52 us=681041 CLIENT/XXXXXX:65165 net_addr_v4_del: 10.61.0.1 dev tun3
2023-09-27 19:04:52 us=683371 CLIENT/XXXXXX:65165 net_iface_del: delete tun3
````

Then consistently see kernel errors

````
Message from syslogd@ip-XXXXX at Sep 27 23:18:39 ...
 kernel:[11843724.403314] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
````

dmesg output
````
……
[11843714.323165] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843724.403314] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843734.483472] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843744.563620] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843754.643777] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843764.723930] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843774.836075] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843784.948232] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843795.060380] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843805.140526] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843815.220675] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843825.300839] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843835.412986] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843845.525133] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843855.637290] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843865.717444] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
[11843875.797583] unregister_netdevice: waiting for tun3 to become free. Usage count = 8
……
````

What can I do about it?

**Comment by ordex** [comment] 2023-09-27 15:26
duplicate of #50

**Closed by ordex** 2023-09-27 15:26 UTC
