### ISSUE TITLE
Backtrace on modprobe...

### ISSUE THREAD

**Issue by hildeb** [OpenVPN/ovpn-dco#10] opened 2022-12-21 14:55 UTC
$ uname -a
Linux comet 5.19.0-28-generic #29-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec 15 09:37:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[  114.066628] ------------[ cut here ]------------
[  114.066635] WARNING: CPU: 2 PID: 15027 at lib/nlattr.c:117 nla_get_range_unsigned+0xe9/0x150
[  114.066656] Modules linked in: sctp libcrc32c ovpn_dco(OE) ip6_udp_tunnel udp_tunnel ccm rfcomm snd_seq_dummy snd_hrtimer cmac algif_hash algif_skcipher af_alg bnep binfmt_misc zfs(PO) zunicode(PO) zzstd(O) zlua(O) zavl(PO) icp(PO) zcommon(PO) znvpair(PO) spl(O) snd_hda_codec_hdmi snd_ctl_led snd_hda_codec_realtek snd_hda_codec_generic btusb btrtl btbcm btintel btmtk bluetooth ecdh_generic ecc uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_common videodev mc dell_rbtn snd_soc_avs snd_soc_skl snd_soc_hdac_hda snd_hda_ext_core snd_soc_sst_ipc snd_soc_sst_dsp snd_soc_acpi_intel_match snd_soc_acpi snd_soc_core snd_compress ac97_bus snd_pcm_dmaengine snd_hda_intel intel_tcc_cooling x86_pkg_temp_thermal intel_powerclamp snd_intel_dspcfg coretemp snd_intel_sdw_acpi snd_hda_codec snd_hda_core kvm_intel snd_hwdep iwlmvm joydev dell_laptop mei_hdcp i915 mei_pxp kvm snd_pcm mac80211 intel_rapl_msr crct10dif_pclmul snd_seq_midi snd_seq_midi_event ghash_clmulni_intel
[  114.066852]  dell_smm_hwmon snd_rawmidi libarc4 aesni_intel drm_buddy ttm crypto_simd snd_seq cryptd drm_display_helper dell_wmi iwlwifi ledtrig_audio cec rapl processor_thermal_device_pci_legacy rc_core snd_seq_device dell_wmi_sysman processor_thermal_device intel_cstate input_leds intel_wmi_thunderbolt processor_thermal_rfim firmware_attributes_class snd_timer drm_kms_helper dell_smbios cfg80211 processor_thermal_mbox dcdbas processor_thermal_rapl i2c_algo_bit wmi_bmof serio_raw snd fb_sys_fops ucsi_acpi mei_me syscopyarea dell_wmi_descriptor ee1004 intel_rapl_common sysfillrect soundcore typec_ucsi hid_multitouch sysimgblt mei nls_iso8859_1 intel_xhci_usb_role_switch intel_soc_dts_iosf typec intel_pch_thermal int3400_thermal int3403_thermal acpi_thermal_rel int340x_thermal_zone dell_smo8800 acpi_pad mac_hid intel_hid sparse_keymap msr parport_pc ppdev lp parport drm pstore_blk ramoops pstore_zone reed_solomon efi_pstore ip_tables x_tables autofs4 usbhid hid_generic rtsx_pci_sdmmc
[  114.067032]  crc32_pclmul e1000e i2c_i801 ahci rtsx_pci i2c_smbus intel_lpss_pci xhci_pci intel_lpss libahci i2c_hid_acpi xhci_pci_renesas idma64 i2c_hid wmi hid video
[  114.067074] CPU: 2 PID: 15027 Comm: openvpn Tainted: P     U     OE     5.19.0-28-generic #29-Ubuntu
[  114.067082] Hardware name: Dell Inc. Latitude 5590/0MM81M, BIOS 1.21.0 01/17/2022
[  114.067087] RIP: 0010:nla_get_range_unsigned+0xe9/0x150
[  114.067098] Code: ff ff 00 00 3c 0b 0f 84 72 ff ff ff 48 c7 c2 ff ff ff ff 3c 04 0f 84 63 ff ff ff 0f 0b 31 c0 31 d2 31 f6 31 ff c3 cc cc cc cc <0f> 0b 48 c7 06 00 00 00 00 0f b6 07 3c 03 0f 85 31 ff ff ff ba ff
[  114.067105] RSP: 0018:ffffb72c46e777a0 EFLAGS: 00010286
[  114.067112] RAX: 0000000000000000 RBX: 000000000000000b RCX: 0000000000000069
[  114.067117] RDX: ffffb72c46e77b18 RSI: ffffb72c46e777b8 RDI: ffffffffc128db70
[  114.067122] RBP: ffffb72c46e777f8 R08: ffffb72c46e777b8 R09: 0000000000000001
[  114.067127] R10: ffffb72c46e77b18 R11: 0000000000000000 R12: ffffffffc128db70
[  114.067132] R13: ffff942e129ee428 R14: ffffb72c46e77b18 R15: 0000000000000000
[  114.067137] FS:  00007f4df6e4f800(0000) GS:ffff94311f480000(0000) knlGS:0000000000000000
[  114.067143] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  114.067148] CR2: 0000555e122f3ae0 CR3: 0000000150e02003 CR4: 00000000003706e0
[  114.067154] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  114.067158] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  114.067163] Call Trace:
[  114.067166]  <TASK>
[  114.067170]  ? nla_validate_int_range+0x81/0x2d0
[  114.067191]  validate_nla+0x4b3/0x790
[  114.067201]  ? __cgroup_account_cputime+0x2f/0x60
[  114.067213]  ? newidle_balance+0x325/0x4b0
[  114.067226]  __nla_validate_parse+0x11f/0x190
[  114.067239]  validate_nla+0x221/0x790
[  114.067248]  ? psi_task_switch+0xc9/0x240
[  114.067257]  ? raw_spin_rq_unlock+0x10/0x40
[  114.067268]  __nla_validate_parse+0x11f/0x190
[  114.067280]  __nla_parse+0x23/0x40
[  114.067289]  genl_family_rcv_msg_attrs_parse.constprop.0+0x93/0x100
[  114.067304]  genl_family_rcv_msg_doit+0x77/0x180
[  114.067320]  genl_rcv_msg+0xf0/0x200
[  114.067330]  ? ovpn_netlink_get_peer+0x1f0/0x1f0 [ovpn_dco]
[  114.067349]  ? genl_get_cmd+0x120/0x120
[  114.067359]  netlink_rcv_skb+0x54/0x110
[  114.067372]  genl_rcv+0x28/0x50
[  114.067380]  netlink_unicast+0x244/0x390
[  114.067392]  netlink_sendmsg+0x25e/0x4e0
[  114.067405]  sock_sendmsg+0x6a/0x70
[  114.067416]  ____sys_sendmsg+0x277/0x2c0
[  114.067425]  ? import_iovec+0x1b/0x30
[  114.067440]  ___sys_sendmsg+0x96/0xe0
[  114.067460]  __sys_sendmsg+0x86/0xf0
[  114.067472]  __x64_sys_sendmsg+0x1d/0x30
[  114.067478]  do_syscall_64+0x58/0x90
[  114.067486]  ? irqentry_exit+0x43/0x50
[  114.067496]  ? exc_page_fault+0x91/0x1b0
[  114.067506]  entry_SYSCALL_64_after_hwframe+0x63/0xcd
[  114.067517] RIP: 0033:0x7f4df6d208d4
[  114.067525] Code: 15 31 55 0d 00 f7 d8 64 89 02 48 c7 c0 ff ff ff ff eb b7 0f 1f 00 f3 0f 1e fa 80 3d 0d dd 0d 00 00 74 13 b8 2e 00 00 00 0f 05 <48> 3d 00 f0 ff ff 77 54 c3 0f 1f 00 48 83 ec 28 89 54 24 1c 48 89
[  114.067530] RSP: 002b:00007ffc97ab1108 EFLAGS: 00000202 ORIG_RAX: 000000000000002e
[  114.067538] RAX: ffffffffffffffda RBX: 0000555e1231d790 RCX: 00007f4df6d208d4
[  114.067543] RDX: 0000000000000000 RSI: 00007ffc97ab1140 RDI: 0000000000000004
[  114.067547] RBP: 0000555e123213d0 R08: 0000555e1232a828 R09: 0000000000000000
[  114.067551] R10: 0000000000000000 R11: 0000000000000202 R12: 0000555e12320af0
[  114.067555] R13: 00007ffc97ab1140 R14: 00007ffc97ab1340 R15: 0000000000000000
[  114.067567]  </TASK>
[  114.067570] ---[ end trace 0000000000000000 ]---

**Comment by bernhardschmidt** [comment] 2023-01-05 09:21
Same on Linux eduvpn-n09 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

**Comment by ordex** [comment] 2023-01-05 09:42
thanks for the report!

**Comment by ordex** [comment] 2023-01-23 23:02
duplicate of #21

**Closed by ordex** 2023-01-23 23:02 UTC
Labels: bug
